### ISSUE TITLE
Create the UI of user- Hospital Part-1 (Patient Details)

### ISSUE THREAD

**Issue by Yadrishi** [upes-open/OSoC-Ambulance-Tracking-App#11]
There are 3 different views in this application- Client, Hospital and Driver.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under osoc'23

**Comment by Yadrishi** [comment]
Sure!

**Comment by karthiknadar1204** [comment]
Do you have any figma file or a colour scheme to be followed @Yadrishi

**Comment by Yadrishi** [comment]
No. That is your creativity. You can send me a sample if you have.

**Comment by karthiknadar1204** [comment]
Works, will share a preview when done

**Comment by Yadrishi** [comment]
Hello @karthiknadar1204 ! Hope you are doing well. Are you working on this issue? Please let me know.

**Comment by Charu-2718** [comment]
Can I work on this issue?

**Comment by Yadrishi** [comment]
Sure.
