### ISSUE TITLE
Create the UI of user- Driver

### ISSUE THREAD

**Issue by Yadrishi** [upes-open/OSoC-Ambulance-Tracking-App#12]
Driver must be able to see options for: Current Booking, Call Patient, Call Hospital, live location.
Can use your own creativity to add more features.

**Comment by AmanKumarVlgs** [comment]
Hey @Yadrishi I want to work on this issue, please assign me this

**Comment by AmanKumarVlgs** [comment]
Thank you for assigning me this, I'll get back to you ASAP.

**Comment by Yadrishi** [comment]
Hello @AmanKumarVlgs  ! Hope you are doing well. Are you working on this issue? Please let me know.

**Comment by Charu-2718** [comment]
Can I work on this issue?

**Comment by Yadrishi** [comment]
Sure!
