### ISSUE TITLE
Create a login/signup screen with 3 views- Hospital, Driver, Client

### ISSUE THREAD

**Issue by Yadrishi** [upes-open/OSoC-Ambulance-Tracking-App#2]
When a user uses the app, he/she must be able to login/ sign up as: Hospital- to receive notification regarding booking of ambulance from client, Driver- to receive notification about the booking, Client- who is the main user here.

**Comment by Yash-Khattar** [comment]
I would like to work on it. Can you specify what all fields are required during signup?

**Comment by Yash-Khattar** [comment]
okay cool, I believe most part of the authentication is done so I'll add the front screen. Also, I've couple of UI changes for auth page color and all, will try to implement that.
