### ISSUE TITLE
Create all the screens of app for CLIENT view after user logs in/ signs in

### ISSUE THREAD

**Issue by Yadrishi** [upes-open/OSoC-Ambulance-Tracking-App#3]
Refer the issue "Create the UI design of ambulance tracking app " for the UI design

**Comment by shradiphylleia** [comment]
would like to work. do you have a design brief in place since #1 isn't done yet?

**Comment by Yadrishi** [comment]
Please tag me on the discord channel of ambulance tracking app, we will have a vc today and I'll explain you everything.
