### ISSUE TITLE
Create a database in MongoDB named 'Feedback' to store the feedbacks.

### ISSUE THREAD

**Issue by Yadrishi** [upes-open/OSoC-Ambulance-Tracking-App#6]
Refer the 'Create a feedback slot for all users' issue.

**Comment by GaganChaudhary6378** [comment]
Hi i want to work on this issue

**Comment by Yadrishi** [comment]
Sure!

**Comment by Charu-2718** [comment]
Can I work on this part?

**Comment by Yadrishi** [comment]
Sure!

**Comment by Charu-2718** [comment]
![image](https://github.com/upes-open/OSoC-Ambulance-Tracking-App/assets/106206014/b9d1a41a-eb78-4ed9-8c08-56fad292053c)
